/**
 * The Companies directory: employers by industry, from the design handoff (nimbus-data.js).
 * Defence, Nuclear and Fusion industries and excluded employers (Airbus, BAE Systems, Boeing…) are
 * left out, as everywhere else in Nimbus. Each entry is "Name|Town".
 */
export const COMPANIES: Record<string, string[]> = {
  "NHS hospitals": ["NHS England graduate schemes|England", "Guy’s and St Thomas’|London", "Manchester University NHS FT|Manchester", "Leeds Teaching Hospitals|Leeds", "Oxford University Hospitals|Oxford", "NHS Scotland|Edinburgh", "NHS Wales|Cardiff"],
  "Clinical research": ["IQVIA|Reading", "ICON|Reading", "Parexel|Uxbridge", "Labcorp|Harrogate", "Syneos Health|Farnborough", "Quotient Sciences|Nottingham"],
  "Community pharmacy": ["Boots|Nottingham", "Well Pharmacy|Manchester", "Superdrug|Croydon", "Rowlands Pharmacy|Runcorn"],
  "Private healthcare": ["Bupa|London", "Spire Healthcare|London", "Nuffield Health|Epsom", "HCA Healthcare UK|London"],
  "Veterinary": ["IVC Evidensia|Bristol", "Medivet|Watford", "CVS Group|Diss", "Vets4Pets|Newport"],
  "Research institutes": ["Francis Crick Institute|London", "Wellcome Sanger Institute|Hinxton", "MRC Laboratory of Molecular Biology|Cambridge", "Rosalind Franklin Institute|Harwell", "The Pirbright Institute|Pirbright", "John Innes Centre|Norwich", "Rothamsted Research|Harpenden", "Babraham Institute|Cambridge"],
  "Genomics": ["Genomics England|London", "Oxford Nanopore|Oxford", "Illumina UK|Cambridge", "Congenica|Cambridge"],
  "Analytical labs": ["Eurofins|Wolverhampton", "LGC|Teddington", "SGS UK|Ellesmere Port", "Intertek|London", "ALS Environmental|Coventry"],
  "Forensics": ["Eurofins Forensic Services|Teddington", "Key Forensic Services|Coventry", "Cellmark|Abingdon", "Scottish Police Authority Forensics|Glasgow"],
  "Food science": ["Campden BRI|Chipping Campden", "Leatherhead Food Research|Epsom", "Quorn Foods|Stokesley", "Greencore|Worksop"],
  "Cosmetics and personal care": ["No7 Beauty Company|Nottingham", "Unilever Beauty & Wellbeing|Port Sunlight", "Estée Lauder UK|London", "Croda|Snaith"],
  "Marine conservation": ["Marine Biological Association|Plymouth", "Marine Conservation Society|Ross-on-Wye", "Cefas|Lowestoft", "Natural England|York", "Seasearch|UK"],
  "Aquaculture and fisheries": ["Mowi Scotland|Fort William", "Scottish Sea Farms|Stirling", "Bakkafrost Scotland|Oban", "Seafish|Grimsby"],
  "Oceanography": ["National Oceanography Centre|Southampton", "Scottish Association for Marine Science|Oban", "Plymouth Marine Laboratory|Plymouth", "British Antarctic Survey|Cambridge"],
  "Ecology and wildlife": ["RSPB|Sandy", "Wildlife Trusts|Newark", "Natural England|York", "Environment Agency|Bristol", "Zoological Society of London|London"],
  "Environmental consultancy": ["RSK Group|Helsby", "Arcadis|London", "Ricardo Energy & Environment|Harwell", "Tetra Tech UK|Bristol"],
  "Zoos and aquariums": ["ZSL London Zoo|London", "Chester Zoo|Chester", "National Marine Aquarium|Plymouth", "Edinburgh Zoo (RZSS)|Edinburgh", "SEA LIFE|UK sites"],
  "Offshore survey": ["Fugro UK|Wallingford", "Gardline|Great Yarmouth", "Ocean Infinity|Southampton"],
  "Public health": ["UK Health Security Agency|London", "Public Health Scotland|Edinburgh", "NICE|Manchester"],
  "Medical communications": ["Ashfield MedComms|Macclesfield", "Healthcare Communications Group|London", "Costello Medical|Cambridge"],
  "Biotech": ["Oxford Nanopore|Oxford", "Abcam|Cambridge", "Oxford Biomedica|Oxford", "Cytiva|Cardiff", "Lonza|Slough", "Fujifilm Diosynth|Billingham"],
  "Diagnostics": ["LumiraDx|Stirling", "Randox|Crumlin", "Abbott Diabetes Care|Witney", "Roche Diagnostics UK|Burgess Hill", "Cepheid UK|Maidenhead"],
  "NHS and clinical engineering": ["NHS Clinical Engineering|UK trusts", "Guy’s and St Thomas’|London", "Leeds Teaching Hospitals|Leeds", "Manchester University NHS FT|Manchester", "NHS Scotland|Edinburgh"],
  "Carbon capture": ["Drax|Selby", "Carbon Clean|Reading", "Storegga|Edinburgh", "Net Zero Teesside|Middlesbrough"],
  "Steel and metals": ["Tata Steel UK|Port Talbot", "British Steel|Scunthorpe", "Outokumpu UK|Sheffield", "Sheffield Forgemasters|Sheffield"],
  "Composites and materials": ["Hexcel|Duxford", "Toray Advanced Composites|Heanor", "Victrex|Thornton-Cleveleys", "National Composites Centre|Bristol", "Morgan Advanced Materials|Windsor"],
  "Machinery and tooling": ["JCB|Rocester", "Caterpillar UK|Peterlee", "Perkins Engines|Peterborough", "Sandvik Coromant UK|Halesowen", "Mazak UK|Worcester"],
  "Packaging": ["Amcor UK|Bristol", "DS Smith|London", "Ball Beverage Packaging|Wakefield", "Crown Packaging|Wantage"],
  "Autonomous vehicles": ["Wayve|London", "Oxa|Oxford", "Five AI (Bosch)|Cambridge", "Aurrigo|Coventry"],
  "Motorcycles": ["Triumph Motorcycles|Hinckley", "Norton Motorcycles|Solihull", "Royal Enfield UK Tech Centre|Bruntingthorpe"],
  "Energy storage": ["Zenobē|London", "Invinity Energy Systems|Bathgate", "Highview Power|London", "Connected Energy|Newcastle"],
  "Sports equipment": ["Brompton Bicycle|London", "Hope Technology|Barnoldswick", "Speedo|Nottingham", "Adidas UK|Stockport"],
  "Audio and music tech": ["Bowers & Wilkins|Worthing", "Focusrite|High Wycombe", "Cambridge Audio|London", "Naim Audio|Salisbury"],
  "Climate tech": ["Octopus Energy|London", "Ceres Power|Horsham", "Pod Point|London", "Mixergy|Oxford"],
  "Agritech": ["CNH Industrial UK|Basildon", "AGCO UK|Stoneleigh", "Small Robot Company|Salisbury", "Intelligent Growth Solutions|Invergowrie"],
  "Motorsport": ["McLaren Racing|Woking", "Mercedes-AMG Petronas F1|Brackley", "Red Bull Racing|Milton Keynes", "Williams Racing|Grove", "Aston Martin Aramco F1|Silverstone", "Alpine F1 Team|Enstone", "Cosworth|Northampton", "Prodrive|Banbury", "Xtrac|Thatcham", "M-Sport|Cockermouth", "Ilmor Engineering|Brixworth", "Mercedes AMG High Performance Powertrains|Brixworth"],
  "Automotive": ["Jaguar Land Rover|Gaydon", "Nissan|Sunderland", "Toyota UK|Burnaston", "BMW Group Plant Oxford|Oxford", "Bentley Motors|Crewe", "Rolls-Royce Motor Cars|Goodwood", "Aston Martin Lagonda|Gaydon", "Lotus|Hethel", "McLaren Automotive|Woking", "Triumph Motorcycles|Hinckley", "JCB|Rocester", "Ford UK|Dunton", "Cummins|Darlington", "Leyland Trucks|Leyland", "GKN Automotive|Birmingham", "Ricardo|Shoreham"],
  "EV and batteries": ["AESC UK|Sunderland", "Agratas|Somerset", "Hyperdrive Innovation|Sunderland", "Ilika|Southampton", "Nexeon|Abingdon", "Johnson Matthey|London", "Turntide Technologies|Sunderland", "Equipmake|Norwich"],
  "Civil aerospace": ["Rolls-Royce|Derby", "GE Aerospace|Cheltenham", "GKN Aerospace|Filton", "Safran Landing Systems|Gloucester", "Spirit AeroSystems|Belfast", "Marshall Aerospace|Cambridge", "Collins Aerospace|Wolverhampton", "Moog|Tewkesbury", "Martin-Baker|Denham", "Vertical Aerospace|Bristol"],
  "Space and satellites": ["Surrey Satellite Technology|Guildford", "Orbex|Forres", "Skyrora|Edinburgh", "Oxford Space Systems|Harwell", "Open Cosmos|Harwell", "AAC Clyde Space|Glasgow", "Astroscale UK|Harwell", "Magdrive|Harwell"],
  "Rail": ["Network Rail|Milton Keynes", "Siemens Mobility|Chippenham", "Alstom|Derby", "Hitachi Rail|Newton Aycliffe", "Wabtec|Doncaster", "CAF UK|Newport", "Transport for London|London", "HS2|Birmingham", "Porterbrook|Derby"],
  "Wind and solar": ["Ørsted UK|London", "RWE|Swindon", "SSE Renewables|Perth", "ScottishPower|Glasgow", "Vestas UK|Isle of Wight", "Siemens Gamesa|Hull", "Octopus Energy|London", "Equinor UK|London"],
  "Power grid and utilities": ["National Grid|Warwick", "UK Power Networks|London", "SP Energy Networks|Glasgow", "Northern Powergrid|Newcastle", "Centrica|Windsor"],
  "Hydrogen": ["ITM Power|Sheffield", "Ceres Power|Horsham", "Johnson Matthey|Billingham", "Intelligent Energy|Loughborough"],
  "Oil and gas": ["BP|Sunbury", "Shell|London", "Wood|Aberdeen", "Harbour Energy|Aberdeen", "TotalEnergies UK|Aberdeen"],
  "Consumer products": ["Dyson|Malmesbury", "Unilever|Port Sunlight", "Procter & Gamble|Newcastle", "Reckitt|Hull", "Haleon|Weybridge", "Kärcher UK|Banbury", "Brompton Bicycle|London"],
  "Food and drink manufacturing": ["Müller UK & Ireland|Telford", "Nestlé UK|York", "Mondelez|Bournville", "PepsiCo UK|Leicester", "Kerry|UK sites", "Diageo|Scotland", "Heineken UK|Manchester", "Coca-Cola Europacific Partners|Uxbridge", "Britvic|Hemel Hempstead", "Mars|Slough"],
  "Robotics": ["Ocado Technology|Hatfield", "Shadow Robot|London", "Oxa|Oxford", "Wayve|London", "Automata|London", "Dexory|Wallingford", "ABB UK|Warrington", "Festo UK|Northampton"],
  "Industrial automation": ["Siemens Digital Industries|Manchester", "Rockwell Automation|Milton Keynes", "Beckhoff UK|Coventry", "Renishaw|Wotton-under-Edge", "Spirax Group|Cheltenham"],
  "Semiconductors": ["Arm|Cambridge", "IQE|Cardiff", "Graphcore|Bristol", "Alphawave Semi|London", "Cirrus Logic UK|Edinburgh", "Infineon UK|Bristol", "Imagination Technologies|Kings Langley"],
  "Electronics and hardware": ["Raspberry Pi|Cambridge", "Sony UK TEC|Pencoed", "Oxford Instruments|Abingdon", "Plextek|Great Chesterford", "e2v Teledyne|Chelmsford"],
  "Medtech and devices": ["Smith+Nephew|Hull", "GE HealthCare|Amersham", "Siemens Healthineers|Oxford", "Medtronic UK|Watford", "Stryker UK|Newbury", "DePuy Synthes|Leeds", "Owen Mumford|Oxford", "Convatec|Deeside"],
  "Surgical robotics": ["CMR Surgical|Cambridge", "Moon Surgical UK|London", "Distalmotion UK|London"],
  "Prosthetics and orthotics": ["Blatchford|Basingstoke", "Ottobock UK|Salford", "Open Bionics|Bristol"],
  "Pharmaceuticals": ["GSK|Stevenage", "AstraZeneca|Macclesfield", "Pfizer UK|Sandwich", "Ineos|London", "Croda|Snaith", "Syngenta|Jealott’s Hill"],
  "Construction": ["Balfour Beatty|London", "Laing O’Rourke|Dartford", "Kier|Bedford", "Costain|Maidenhead", "Mace|London", "Skanska UK|Rickmansworth", "Galliford Try|Uxbridge"],
  "Infrastructure": ["Arup|London", "AtkinsRéalis|Epsom", "Mott MacDonald|Croydon", "Jacobs|London", "WSP|London", "AECOM|London", "Stantec|London"],
  "Structural consultancy": ["Buro Happold|Bath", "Ramboll|London", "Price & Myers|London", "Expedition Engineering|London"],
  "Water and wastewater": ["Thames Water|Reading", "Severn Trent|Coventry", "United Utilities|Warrington", "Anglian Water|Peterborough", "Yorkshire Water|Bradford", "Scottish Water|Dunfermline"],
  "Marine and shipbuilding": ["Princess Yachts|Plymouth", "Sunseeker|Poole", "INEOS Britannia|Portsmouth", "Lloyd’s Register|Southampton"],
  "Engineering consultancy": ["Cambridge Consultants|Cambridge", "TTP|Melbourn", "PA Consulting|Cambridge", "Ricardo|Shoreham"],
  "R&D labs": ["TWI|Cambridge", "Manufacturing Technology Centre|Coventry", "AMRC|Sheffield", "National Physical Laboratory|Teddington", "High Value Manufacturing Catapult|UK sites"],
};

/** Industries every degree in a field sees, on top of the degree's own suggestions. */
export const FIELD_EXTRAS: Record<string, string[]> = {
  Engineering: ["Engineering consultancy", "R&D labs"],
  Science: ["Research institutes", "Analytical labs"],
  "Medical and health": ["NHS hospitals", "Clinical research"],
};
